### ISSUE TITLE
The problem of Alluvial plot repeatability

### ISSUE THREAD

**Issue by hansir8** [hleffler/REU-microbial-visualization#4]
Dear Haley Leffler,
    Thanks so much for your sharing the microbial visualization scripts. It helps me learning the methods of handling metagenome data, which was valuable in this field. However, I meet a problem about  the section of your Alluvial plot, which show how sets of groups change according to differnt variables. I could not get the "phylumreformat.csv" file, even though the "kraken_report_phylum_percent.csv" have been provided. I did not understand the meaning of "The file was reformatted to have every variable in a column. This is necessary for the alluvial plot script. Taxa phylum with low abundance was grouped into one taxa called "Other". Other variables from the data set were added such as location, thermogenic gases detected, hydrocarbons detected, and sample names from the published paper", which was provided in the Github. Although I tried several methods to solve this problem, it was unsuccessful in the end. Could you  provide the phylumreformat.csv" file for me or tell me the detailed flow to generate this file? 

Thanks again!
Zhenzhi Han
2021/06/19

**Comment by hleffler** [comment]
Hi Zhenzhi Han!

Thank you for reaching out about this issue! I spent several days trying to figure out how to create an alluvial plot with my data. If you look at the "kraken_report_phylum_percent.csv" file, you see how the samples run across the top of the table with percentages of abundance listed below for each taxa. So, each sample has its own column. The taxa also has its own column listing the names of each identified phylum. When you try using the format of this file the alluvial plot does not look right. 

To reformat the file to create a pretty plot, your data needs to be in columns. I made three columns with the headers as: sample, taxa (phylum), and abundance. This means that you will have the same sample number listed in the sample column multiple times depending on the number of identified taxa. Also your taxa will be repeated in the taxa column-- This is why I used only the most abundant taxa and grouped the low abundant into "other." Your data should be reformatted to look something like this: 

| Sample | Taxa | Abundance |
|-|-|-|
| sample1 | Proteobacteria | 1.41 |
| sample1 | Actinobacteria | 3.37 |
| sample1 | Firmicutes | 1.29 |
| sample2 | Proteobacteria | 2.54 |
| sample2 | Actinobacteria | 1.45 |
| sample2 | Firmicutes | 2.31 |
| sample3 | Proteobacteria | 1.32 |
| sample3 | Actinobacteria | 4.11 |
| sample3 | Firmicutes | 1.31 |

The phylumreformat.csv file will be available in the [input_data](https://github.com/hleffler/Microbial-visualization/tree/master/input_data) folder so you can try this yourself and I will consider this issue closed. I also recommend you to explore the [ggalluvial GitHub](https://corybrunson.github.io/ggalluvial/index.html) to look at further examples and other things you can do with ggalluival!
